modLoader="javafml"
loaderVersion="[2,)"
license="All Rights Reserved"

[[mods]]
modId="bad_mod"
version="0.0.0"
displayName="Bad Mod"
displayURL="https://github.com/OBX555/BadMod.git"
credits="OBX555, tyuXX"
authors="OBX555"
description="Its a bad mod or is it? Vsauce theme plays"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.bad_mod]]
    modId="neoforge"
    type="required"
    versionRange="[20.6.117,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.bad_mod]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.6]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration